name: ci

on:
  push:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: Push README to Dockerhub
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
        with:
          destination_container_repo: stevenmassaro/recurring-task-base
          provider: dockerhub
          short_description: ${{ github.event.repository.description }}
          readme_file: 'README.md'
      - name: Determine alpine version
        id: version
        run: echo "VERSION=$(head Dockerfile -n 1 | cut -d ':' -f2)" >> $GITHUB_OUTPUT
      - name: Determine local version
        id: local-version
        run: echo "LOCAL_VERSION=$(head version.txt -n 1)" >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            stevenmassaro/recurring-task-base:latest
            stevenmassaro/recurring-task-base:v${{ steps.local-version.outputs.LOCAL_VERSION}}.${{ steps.version.outputs.VERSION }}